### ISSUE TITLE
FCS selecting the wrong FCS on output

### ISSUE THREAD

**Issue by fmadio** [fmadio/pcap_decap#1]

**Comment by sevagen** [comment]
Original gre pcap 
16:16:33.916033 a8:0c:0d:b0:46:3c > 01:00:5e:2d:08:5d, ethertype IPv4 (0x0800), length 118: 10.173.8.89 > 10.173.8.93: GREv0, seq 872644064, proto unknown (0x22eb), length 80: gre-proto-0x22eb
        0x0000:  0100 5e2d 085d a80c 0db0 463c 0800 4500  ..^-.]....F<..E.
        0x0010:  0064 0000 4000 0d2f 475c 0aad 0859 0aad  .d..@../G\...Y..
        0x0020:  085d 1000 22eb 3403 7de0 2000 0001 377c  .]..".4.}.....7|
        0x0030:  a5e0 0001 0276 0000 0c07 acf1 0010 dbff  .....v..........
        0x0040:  1002 0800 4500 0028 5782 4000 7c06 11ff  ....E..(W.@.|...
        0x0050:  0a84 2608 a37c c146 ebfd 4a35 fb74 278f  ..&..|.F..J5.t'.
        0x0060:  7bdc 2846 5010 00fb 1c31 0000 0000 0000  {.(FP....1......
        0x0070:  0000 765c fcb5  

erspan2pcap version
16:16:33.916033 00:10:db:ff:10:02 > 00:00:0c:07:ac:f1, ethertype IPv4 (0x0800), length 64: 10.132.38.8.60413 > 163.124.193.70.18997: Flags [.], ack 2078025798, win 251, length 0
        0x0000:  0000 0c07 acf1 0010 dbff 1002 0800 4500  ..............E.
        0x0010:  0028 5782 4000 7c06 11ff 0a84 2608 a37c  .(W.@.|.....&..|
        0x0020:  c146 ebfd 4a35 fb74 278f 7bdc 2846 5010  .F..J5.t'.{.(FP.
        0x0030:  00fb 1c31 0000 0000 0000 0000 765c fcb5  ...1........v\..

According to wireshark, 
Frame check sequence: 0x765cfcb5 incorrect, should be 0x03a27f1b

**Comment by fmadio** [comment]
ERSPAN does not keep the orignial FCS value, thus FCS after de-encapsulation will always be invalid.
