### ISSUE TITLE
GRE Seq no showing invalid packet drops

### ISSUE THREAD

**Issue by fmadio** [fmadio/pcap_decap#2]

**Comment by sevagen** [comment]
Here is an example - fairly small pcap file with rather large count of packet drops. 
[svcegcts@tkadminlab8 ~]$ ./erspan2pcap-20150203a -i erspan_is_back_no_gap_20180702_1616_download.pcap -o seva.pcap 
erspan2pcap utility by http://fmad.io : contact support@fmad.io : Version Feb  3 2015 23:33:46
Nano PCAP
ERSpan Histo
          V1 :            0 Pkts
          V2 :            0 Pkts
          V3 :      606,361 Pkts
Port histo
     Ingress
           1 :      606,135 Pkts
           2 :          226 Pkts
GRE Session
          Ingress : Pkts:     606,361 Drops:  36,744,853 Gaps:     583,516
0 0 0
[svcegcts@tkadminlab8 ~]$

**Comment by fmadio** [comment]
With the new code exact same number... theres a logic error somewhere.

ERSPAN Session:00000020 PktCnt:  606361 Bytes:353060948 Drop:37328369 GapCnt:583516

**Comment by fmadio** [comment]
beleive this pcap the erspan session has significant packet loss. numbers are expected closing.
